# Generated by Django 5.0.3 on 2025-11-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='style',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
